### ISSUE TITLE
Map, sfx, overwritten on save

### ISSUE THREAD

**Issue by prettymuchbryce** [AgronKabashi/rollup-plugin-jspicl#7]
It looks like with cartridge version 16, the map and the sfx are occasionally being overwritten to the default (blank) on save. My guess is that it could be something to do with the way the cartridge format has changed since this project was last updated.

**Comment by AgronKabashi** [comment]
Thanks for reporting this. It seems that with version 16 pico-8 no longer outputs the full data for each segment so `generateCartridge` probably needs to be updated accordingly. I'll investigate this further and take look at your PR as soon as possible.

**Comment by AgronKabashi** [comment]
Fixed in #8

**Comment by prettymuchbryce** [comment]
Thanks @AgronKabashi !
